# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _matrix
else:
    import _matrix

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _matrix.delete_SwigPyIterator

    def value(self):
        return _matrix.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _matrix.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _matrix.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _matrix.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _matrix.SwigPyIterator_equal(self, x)

    def copy(self):
        return _matrix.SwigPyIterator_copy(self)

    def next(self):
        return _matrix.SwigPyIterator_next(self)

    def __next__(self):
        return _matrix.SwigPyIterator___next__(self)

    def previous(self):
        return _matrix.SwigPyIterator_previous(self)

    def advance(self, n):
        return _matrix.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _matrix.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _matrix.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _matrix.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _matrix.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _matrix.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _matrix.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _matrix:
_matrix.SwigPyIterator_swigregister(SwigPyIterator)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _matrix.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _matrix.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _matrix.DoubleVector___bool__(self)

    def __len__(self):
        return _matrix.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _matrix.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _matrix.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _matrix.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _matrix.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _matrix.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _matrix.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _matrix.DoubleVector_pop(self)

    def append(self, x):
        return _matrix.DoubleVector_append(self, x)

    def empty(self):
        return _matrix.DoubleVector_empty(self)

    def size(self):
        return _matrix.DoubleVector_size(self)

    def swap(self, v):
        return _matrix.DoubleVector_swap(self, v)

    def begin(self):
        return _matrix.DoubleVector_begin(self)

    def end(self):
        return _matrix.DoubleVector_end(self)

    def rbegin(self):
        return _matrix.DoubleVector_rbegin(self)

    def rend(self):
        return _matrix.DoubleVector_rend(self)

    def clear(self):
        return _matrix.DoubleVector_clear(self)

    def get_allocator(self):
        return _matrix.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _matrix.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _matrix.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _matrix.DoubleVector_swiginit(self, _matrix.new_DoubleVector(*args))

    def push_back(self, x):
        return _matrix.DoubleVector_push_back(self, x)

    def front(self):
        return _matrix.DoubleVector_front(self)

    def back(self):
        return _matrix.DoubleVector_back(self)

    def assign(self, n, x):
        return _matrix.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _matrix.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _matrix.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _matrix.DoubleVector_reserve(self, n)

    def capacity(self):
        return _matrix.DoubleVector_capacity(self)
    __swig_destroy__ = _matrix.delete_DoubleVector

# Register DoubleVector in _matrix:
_matrix.DoubleVector_swigregister(DoubleVector)

class DoubleDoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _matrix.DoubleDoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _matrix.DoubleDoubleVector___nonzero__(self)

    def __bool__(self):
        return _matrix.DoubleDoubleVector___bool__(self)

    def __len__(self):
        return _matrix.DoubleDoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _matrix.DoubleDoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _matrix.DoubleDoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _matrix.DoubleDoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _matrix.DoubleDoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _matrix.DoubleDoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _matrix.DoubleDoubleVector___setitem__(self, *args)

    def pop(self):
        return _matrix.DoubleDoubleVector_pop(self)

    def append(self, x):
        return _matrix.DoubleDoubleVector_append(self, x)

    def empty(self):
        return _matrix.DoubleDoubleVector_empty(self)

    def size(self):
        return _matrix.DoubleDoubleVector_size(self)

    def swap(self, v):
        return _matrix.DoubleDoubleVector_swap(self, v)

    def begin(self):
        return _matrix.DoubleDoubleVector_begin(self)

    def end(self):
        return _matrix.DoubleDoubleVector_end(self)

    def rbegin(self):
        return _matrix.DoubleDoubleVector_rbegin(self)

    def rend(self):
        return _matrix.DoubleDoubleVector_rend(self)

    def clear(self):
        return _matrix.DoubleDoubleVector_clear(self)

    def get_allocator(self):
        return _matrix.DoubleDoubleVector_get_allocator(self)

    def pop_back(self):
        return _matrix.DoubleDoubleVector_pop_back(self)

    def erase(self, *args):
        return _matrix.DoubleDoubleVector_erase(self, *args)

    def __init__(self, *args):
        _matrix.DoubleDoubleVector_swiginit(self, _matrix.new_DoubleDoubleVector(*args))

    def push_back(self, x):
        return _matrix.DoubleDoubleVector_push_back(self, x)

    def front(self):
        return _matrix.DoubleDoubleVector_front(self)

    def back(self):
        return _matrix.DoubleDoubleVector_back(self)

    def assign(self, n, x):
        return _matrix.DoubleDoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _matrix.DoubleDoubleVector_resize(self, *args)

    def insert(self, *args):
        return _matrix.DoubleDoubleVector_insert(self, *args)

    def reserve(self, n):
        return _matrix.DoubleDoubleVector_reserve(self, n)

    def capacity(self):
        return _matrix.DoubleDoubleVector_capacity(self)
    __swig_destroy__ = _matrix.delete_DoubleDoubleVector

# Register DoubleDoubleVector in _matrix:
_matrix.DoubleDoubleVector_swigregister(DoubleDoubleVector)

class MyMatrix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rows = property(_matrix.MyMatrix_rows_get, _matrix.MyMatrix_rows_set)
    cols = property(_matrix.MyMatrix_cols_get, _matrix.MyMatrix_cols_set)
    data = property(_matrix.MyMatrix_data_get, _matrix.MyMatrix_data_set)

    def __init__(self, *args):
        _matrix.MyMatrix_swiginit(self, _matrix.new_MyMatrix(*args))

    def __add__(self, other):
        return _matrix.MyMatrix___add__(self, other)
    __swig_destroy__ = _matrix.delete_MyMatrix

# Register MyMatrix in _matrix:
_matrix.MyMatrix_swigregister(MyMatrix)


def setUpLibrary():
    return _matrix.setUpLibrary()

def tearDownLibrary():
    return _matrix.tearDownLibrary()


